replicaCount: 1

image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
  tag: "2.20.15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  containerPort: 8000

env:
  PAPERLESS_URL: "https://paperless.6940469.xyz"
  PAPERLESS_DBENGINE: postgresql
  PAPERLESS_DBHOST: postgresql.databases.svc.cluster.local
  PAPERLESS_DBPORT: "5432"
  PAPERLESS_DBNAME: paperless
  PAPERLESS_OCR_LANGUAGE: eng
  PAPERLESS_TIME_ZONE: "Europe/London"

envFromSecrets:
  - secretName: paperless-credentials
    keys:
      PAPERLESS_SECRET_KEY: secret-key
      PAPERLESS_ADMIN_USER: admin-user
      PAPERLESS_ADMIN_PASSWORD: admin-password
  - secretName: paperless-database
    keys:
      PAPERLESS_DBPASS: password
      PAPERLESS_DBUSER: username
  - secretName: redis-client
    keys:
      PAPERLESS_REDIS: redis-url

persistence:
  data:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
    mountPath: /usr/src/paperless/data
    storageClass: ""
  media:
    enabled: true
    size: 20Gi
    accessMode: ReadWriteOnce
    mountPath: /usr/src/paperless/media
    storageClass: ""

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
