k3s_cluster:
  children:
    agent:
      hosts:
        localhost:
          ansible_connection: local
  vars:
    k3s_version: v1.33.1+k3s1
    ansible_user: ansible
    api_endpoint: "10.0.1.1"
    extra_server_args: "--secrets-encryption"