redis:
  architecture: standalone
  auth:
    enabled: true
    existingSecret: redis-credentials
    existingSecretPasswordKey: redis-password
  master:
    persistence:
      enabled: true
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  networkPolicy:
    enabled: true
    allowExternal: false
    allowExternalEgress: false
    extraIngress:
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: paperless-ngx
        ports:
          - protocol: TCP
            port: 6379
    extraEgress:
      - to:
          - namespaceSelector: {}
            podSelector:
              matchLabels:
                k8s-app: kube-dns
        ports:
          - {protocol: UDP, port: 53}
          - {protocol: TCP, port: 53}
