apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultwarden-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: applications/vaultwarden
  refreshAfter: 30s
  destination:
    name: vaultwarden-credentials
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultwarden-database
  namespace: {{ .Release.Namespace }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: applications/vaultwarden/database
  refreshAfter: 5m
  destination:
    name: vaultwarden-database
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vaultwarden-oidc
  namespace: {{ .Release.Namespace }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: oauth/vaultwarden
  refreshAfter: 30s
  destination:
    name: vaultwarden-oidc
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
