# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
#ENABLE_LINTERS:

# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

ADDITIONAL_EXCLUDED_DIRECTORIES:
  - docs/node_modules

COPYPASTE_JSCPD_CONFIG_FILE: config/.jscpd.json
SPELL_CSPELL_CONFIG_FILE: config/.cspell.json
HTML_HTMLHINT_CONFIG_FILE: config/.htmlhintrc
REPOSITORY_DEVSKIM_CONFIG_FILE: config/.devskim.json
CSS_STYLELINT_FILTER_REGEX_EXCLUDE: docs/assets/scss/common/.*.scss
REPOSITORY_CHECKOV_ARGUMENTS: --skip-check CKV2_GHA_1,CKV2_ANSIBLE_3
SPELL_LYCHEE_FILTER_REGEX_EXCLUDE: docs/layouts/.*.html|package-lock.json

DISABLE_LINTERS:
  - TERRAFORM_TERRASCAN
  - REPOSITORY_GIT_DIFF
