apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: acme-dns
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: infrastructure/acme-dns
  refreshAfter: 5m
  destination:
    name: acme-dns
    create: true
