metrics-server:
  replicas: 1
  args:
    - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
    - --kubelet-use-node-status-port
    - --metric-resolution=15s
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 250m
      memory: 256Mi
