apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: networking
      ports:
        - {protocol: TCP, port: {{ .Values.service.containerPort }}}
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels: {k8s-app: kube-dns}
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
    - to:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values: [kitchenowl, monitoring, ntfy, paperless-ngx, security, smart-home, vaultwarden]
      ports:
        - {protocol: TCP, port: 80}
        - {protocol: TCP, port: 443}
        - {protocol: TCP, port: 8000}
        - {protocol: TCP, port: 8080}
        - {protocol: TCP, port: 8123}
    - ports:
        - {protocol: TCP, port: 443}
