apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: homepage-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: applications/homepage
  refreshAfter: 30s
  destination:
    name: homepage-auth
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: homepage-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: oauth/homepage
  refreshAfter: 30s
  destination:
    name: homepage-oidc
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
