apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pocket-id-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  vaultAuthRef: security/default
  mount: secret
  type: kv-v2
  path: security/pocket-id
  refreshAfter: 30s
  destination:
    name: pocket-id-credentials
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
