repositories:
  - name: longhorn
    url: https://charts.longhorn.io

releases:
###  CORE CONFIGURATION ###
  - name: namespaces
    chart: ./core/namespaces
    historyMax: 5
    namespace: kube-system
  - name: rbac-policies
    chart: ./core/rbac-policies
    historyMax: 5
    namespace: kube-system
    needs: [kube-system/namespaces]

###  STORAGE CONFIGURATION ###
  - name: longhorn
    chart: ./storage/longhorn
    historyMax: 5
    namespace: longhorn-system
    createNamespace: true

hooks:
  - events: ["prepare"]
    showlogs: true
    command: "kubectl"
    args: ["label", "node", "agent-node-0", "node-role.kubernetes.io/worker=true", "--overwrite"]