apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-boundary
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: monitoring}
    - from:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: networking}
      ports:
        - {protocol: TCP, port: 3000}
    - from:
        - namespaceSelector: {}
      ports:
        - {protocol: TCP, port: 4317}
        - {protocol: TCP, port: 4318}
  egress:
    - to:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: monitoring}
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels: {k8s-app: kube-dns}
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
    - ports:
        - {protocol: TCP, port: 443}
        - {protocol: TCP, port: 6443}
        - {protocol: TCP, port: 8080}
        - {protocol: TCP, port: 8081}
        - {protocol: TCP, port: 8200}
        - {protocol: TCP, port: 9100}
        - {protocol: TCP, port: 10250}
