apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  annotations:
    checkov.io/skip1: "AVD-KSV-0037: Traefik is intentionally deployed in kube-system"
spec:
  valuesContent: |-
    nodeSelector:
      node-role.kubernetes.io/master: "true"