#cloud-config
users:
  - name: ansible
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: true
    ssh-authorized-keys: [ ]
  - name: iamkhattar
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: true
    ssh-authorized-keys: [ ]

package_update: true
package_upgrade: true

packages:
  - ansible-core
  - git

runcmd:
  - su - ansible -s /bin/bash -c "cd /tmp && git clone https://github.com/iamkhattar/homelab.git"
  - su - ansible -s /bin/bash -c "cd /tmp/homelab && git switch feature/ansible-playbook"
#  - su - ansible -s /bin/bash -c "cd /tmp/homelab/k3s && ansible-playbook playbooks/site.yml -i inventory/inventory-server.yml"