#cloud-config
users:
  - name: ansible
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: true
    ssh-authorized-keys:
      - ${local_ssh_public_key}
  - name: iamkhattar
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: true
    ssh-authorized-keys:
      - ${local_ssh_public_key}

package_update: true
package_upgrade: true

packages:
  - ansible-core
  - git
