apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paperless-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: applications/paperless-ngx
  refreshAfter: 30s
  destination:
    name: paperless-credentials
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: paperless-database
  namespace: {{ .Release.Namespace }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: applications/paperless-ngx/database
  refreshAfter: 5m
  destination:
    name: paperless-database
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-client
  namespace: {{ .Release.Namespace }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: applications/paperless-ngx/redis
  refreshAfter: 30s
  destination:
    name: redis-client
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
