---
- name: Upgrade K3s servers and agents
  ansible.builtin.import_playbook: k3s.orchestration.upgrade

- name: Verify the upgraded cluster
  hosts: "server[0]"
  gather_facts: false
  become: true
  tasks:
    - name: Wait for all Kubernetes nodes to become ready
      ansible.builtin.command:
        cmd: k3s kubectl wait --for=condition=Ready node --all --timeout=180s
      changed_when: false
