apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  vaultAuthRef: security/default
  mount: secret
  type: kv-v2
  path: databases/redis
  refreshAfter: 30s
  destination:
    name: redis-credentials
    create: true
  rolloutRestartTargets:
    - kind: StatefulSet
      name: {{ .Release.Name }}-redis-master
