replicaCount: 1

image:
  repository: dxflrs/garage
  tag: "v2.3.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  s3Port: 3900
  rpcPort: 3901
  webPort: 3902
  adminPort: 3903

persistence:
  data:
    enabled: true
    size: 50Gi
    accessMode: ReadWriteOnce
    mountPath: /var/lib/garage/data
    storageClass: ""
  meta:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
    mountPath: /var/lib/garage/meta
    storageClass: ""

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
