apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kitchenowl-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: applications/kitchenowl
  refreshAfter: 30s
  destination:
    name: kitchenowl-credentials
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: kitchenowl-database
  namespace: {{ .Release.Namespace }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: applications/kitchenowl/database
  refreshAfter: 5m
  destination:
    name: kitchenowl-database
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
