apiVersion: v2
name: postgresql
description: A Helm chart to deploy PostgreSQL for the homelab k3s cluster
type: application
version: 0.1.0
appVersion: "16.6.0"
dependencies:
  - name: postgresql
    version: "16.4.3"
    repository: https://charts.bitnami.com/bitnami
