{{- range .Values.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/managed-by: rbac-policies
rules:
  {{- toYaml .rules | nindent 2 }}
{{- end }}
