apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: monitoring/grafana
  refreshAfter: 30s
  destination:
    name: grafana-credentials
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-oidc
  namespace: {{ .Release.Namespace }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: oauth/grafana
  refreshAfter: 30s
  destination:
    name: grafana-oidc
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
