apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgresql-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  vaultAuthRef: security/default
  mount: secret
  type: kv-v2
  path: databases/postgresql
  refreshAfter: 30s
  destination:
    name: postgresql-credentials
    create: true
  rolloutRestartTargets:
    - kind: StatefulSet
      name: {{ .Release.Name }}-postgresql
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgresql-initdb
  namespace: {{ .Release.Namespace }}
spec:
  vaultAuthRef: security/default
  mount: secret
  type: kv-v2
  path: databases/postgresql
  refreshAfter: 5m
  destination:
    name: postgresql-initdb
    create: true
    transformation:
      excludes: [".*"]
      templates:
        init.sql:
          text: '{{ `{{- get .Secrets "init.sql" -}}` }}'
