apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mqtt-credentials
  namespace: {{ .Release.Namespace }}
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: smart-home/mqtt
  refreshAfter: 5m
  destination:
    name: mqtt-credentials
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Release.Name }}
