{{- if $.Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}-default-deny
  namespace: {{ .name }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- if not $.Values.networkPolicies.defaultDeny }}
  ingress:
    - {}
  egress:
    - {}
{{- end }}
{{- end }}