package ci

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/iamkhattar/homelab/hl/internal/lint"
	"github.com/iamkhattar/homelab/hl/internal/ui"
)

var sarifDir string
var sbomDir string

// moduleName converts a relative module path to a filename-safe identifier.
// e.g. "./hl" → "hl", "./services/butler" → "services-butler".
func moduleName(rel string) string {
	name := strings.TrimPrefix(rel, ".")
	name = strings.TrimPrefix(name, "/")
	if name == "" {
		name = "root"
	}
	return strings.ReplaceAll(name, "/", "-")
}

var lintSarifCmd = &cobra.Command{
	Use:   "lint-sarif",
	Short: "Run golangci-lint with SARIF output for all Go modules",
	Long: `Run golangci-lint across every Go module in the repo,
producing a SARIF report per module. Non-zero exits from golangci-lint
are tolerated so that all modules are scanned.`,
	Example: `  hl ci lint-sarif
  hl ci lint-sarif --output-dir sarif/`,
	RunE: func(cmd *cobra.Command, args []string) error {
		root, err := lint.RepoRoot()
		if err != nil {
			return err
		}

		if err := os.MkdirAll(sarifDir, 0755); err != nil {
			return fmt.Errorf("creating sarif dir: %w", err)
		}

		modules, err := lint.FindGoModules(root)
		if err != nil {
			return err
		}

		ui.Step("Running golangci-lint (SARIF)")
		for _, dir := range modules {
			rel, _ := filepath.Rel(root, dir)
			name := moduleName(rel)
			outFile := filepath.Join(sarifDir, fmt.Sprintf("golangci-%s.sarif", name))

			ui.KeyValue("  module", rel)
			c := exec.Command("golangci-lint", "run",
				fmt.Sprintf("--output.sarif.path=%s", outFile), "./...")
			c.Dir = dir
			c.Stdout = os.Stdout
			c.Stderr = os.Stderr
			// Tolerate non-zero exits — we want all modules scanned.
			_ = c.Run()
		}

		ui.StepDone("golangci-lint SARIF complete")
		return nil
	},
}

var gitleaksCmd = &cobra.Command{
	Use:   "gitleaks",
	Short: "Run gitleaks secret scanning with SARIF output",
	Long:  `Scan the repository for secrets using gitleaks, producing a SARIF report.`,
	Example: `  hl ci gitleaks
  hl ci gitleaks --output-dir sarif/`,
	RunE: func(cmd *cobra.Command, args []string) error {
		root, err := lint.RepoRoot()
		if err != nil {
			return err
		}

		if err := os.MkdirAll(sarifDir, 0755); err != nil {
			return fmt.Errorf("creating sarif dir: %w", err)
		}

		outFile := filepath.Join(sarifDir, "gitleaks.sarif")

		ui.Step("Running gitleaks")
		c := exec.Command("gitleaks", "dir", root,
			"--report-format", "sarif",
			"--report-path", outFile)
		c.Stdout = os.Stdout
		c.Stderr = os.Stderr
		// Tolerate non-zero exit — gitleaks returns 1 when findings exist.
		_ = c.Run()

		ui.StepDone("gitleaks scan complete")
		return nil
	},
}

var sbomCmd = &cobra.Command{
	Use:   "sbom",
	Short: "Generate SBOMs (SPDX + CycloneDX) for all Go modules",
	Long: `Run syft against every Go module in the repo, producing
SPDX JSON and CycloneDX JSON SBOMs per module.`,
	Example: `  hl ci sbom
  hl ci sbom --output-dir sbom/`,
	RunE: func(cmd *cobra.Command, args []string) error {
		root, err := lint.RepoRoot()
		if err != nil {
			return err
		}

		if err := os.MkdirAll(sbomDir, 0755); err != nil {
			return fmt.Errorf("creating sbom dir: %w", err)
		}

		modules, err := lint.FindGoModules(root)
		if err != nil {
			return err
		}

		ui.Step("Generating SBOMs (syft)")
		for _, dir := range modules {
			rel, _ := filepath.Rel(root, dir)
			name := moduleName(rel)
			spdxFile := filepath.Join(sbomDir, fmt.Sprintf("%s.spdx.json", name))
			cdxFile := filepath.Join(sbomDir, fmt.Sprintf("%s.cdx.json", name))

			ui.KeyValue("  module", rel)
			c := exec.Command("syft", "scan", fmt.Sprintf("dir:%s", dir),
				"-o", fmt.Sprintf("spdx-json=%s", spdxFile),
				"-o", fmt.Sprintf("cyclonedx-json=%s", cdxFile))
			c.Stdout = os.Stdout
			c.Stderr = os.Stderr
			if err := c.Run(); err != nil {
				return fmt.Errorf("syft %s: %w", rel, err)
			}
		}

		ui.StepDone("SBOM generation complete")
		return nil
	},
}

var vulnscanCmd = &cobra.Command{
	Use:   "vulnscan",
	Short: "Run vulnerability scanning (grype) against SBOMs",
	Long: `Scan SPDX SBOMs with grype, producing a SARIF report per module.
Expects SBOMs in --sbom-dir (generated by hl ci sbom).`,
	Example: `  hl ci vulnscan
  hl ci vulnscan --sbom-dir sbom/ --output-dir sarif/`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := os.MkdirAll(sarifDir, 0755); err != nil {
			return fmt.Errorf("creating sarif dir: %w", err)
		}

		matches, err := filepath.Glob(filepath.Join(sbomDir, "*.spdx.json"))
		if err != nil {
			return err
		}
		if len(matches) == 0 {
			ui.KeyValue("vulnscan", "no SBOMs found, skipping")
			return nil
		}

		ui.Step("Running vulnerability scan (grype)")
		for _, sbom := range matches {
			base := filepath.Base(sbom)
			name := strings.TrimSuffix(base, ".spdx.json")
			outFile := filepath.Join(sarifDir, fmt.Sprintf("grype-%s.sarif", name))

			ui.KeyValue("  scanning", name)
			c := exec.Command("grype", fmt.Sprintf("sbom:%s", sbom),
				"--output", "sarif", "--file", outFile)
			c.Stdout = os.Stdout
			c.Stderr = os.Stderr
			// Tolerate non-zero exit — grype returns non-zero when vulns found.
			_ = c.Run()
		}

		ui.StepDone("vulnerability scan complete")
		return nil
	},
}

func init() {
	// SARIF output dir flag — shared by lint-sarif, gitleaks, vulnscan.
	for _, cmd := range []*cobra.Command{lintSarifCmd, gitleaksCmd, vulnscanCmd} {
		cmd.Flags().StringVar(&sarifDir, "output-dir", "sarif/", "Directory for SARIF output files")
	}

	sbomCmd.Flags().StringVar(&sbomDir, "output-dir", "sbom/", "Directory for SBOM output files")
	vulnscanCmd.Flags().StringVar(&sbomDir, "sbom-dir", "sbom/", "Directory containing SPDX SBOMs")

	Cmd.AddCommand(lintSarifCmd)
	Cmd.AddCommand(gitleaksCmd)
	Cmd.AddCommand(sbomCmd)
	Cmd.AddCommand(vulnscanCmd)
}
