apiVersion: v2
name: opa-gatekeeper
description: A Helm chart to deploy OPA Gatekeeper for the homelab k3s cluster
type: application
version: 0.1.0
appVersion: "3.17.0"
dependencies:
  - name: gatekeeper
    version: "3.17.0"
    repository: https://open-policy-agent.github.io/gatekeeper/charts
