gatekeeper:
  replicas: 1
  audit:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi
  controllerManager:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi
  psp:
    enabled: false
  validatingWebhookFailurePolicy: Ignore  # Fail-open while learning
  enableDeleteOperations: false
