namespaces:
  - name: cert-manager
    labels:
      app.kubernetes.io/component: cert-manager
      6940469.xyz/category: core
  - name: databases
    labels:
      app.kubernetes.io/component: database
      6940469.xyz/category: infrastructure
  - name: storage
    labels:
      app.kubernetes.io/component: storage
      6940469.xyz/category: infrastructure
  - name: monitoring
    labels:
      app.kubernetes.io/component: monitoring
      6940469.xyz/category: observability
  - name: security
    labels:
      app.kubernetes.io/component: security
      6940469.xyz/category: security
  - name: applications
    labels:
      app.kubernetes.io/component: application
      6940469.xyz/category: applications
  - name: smart-home
    labels:
      app.kubernetes.io/component: smart-home
      6940469.xyz/category: applications
  - name: networking
    labels:
      app.kubernetes.io/component: networking
      6940469.xyz/category: infrastructure
  - name: cicd
    labels:
      app.kubernetes.io/component: cicd
      6940469.xyz/category: infrastructure
